title: HumINT 10101
author: Eliyahu Stern
email: contact@humint10101.online
description: Recruitment of IT- and Consulting Specialists, Freelance Translators, and GDPR-Case Analysts.
theme: jekyll-theme-hacker
